version: '2'

services:
  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /gunicorn.sh
    env_file: .env
    container_name: django
    ports:
      - 5000

  nginx:
    build: ./compose/nginx
    links:
      - django
    depends_on:
      - django
    ports:
      - 80:80
      - 443:443
    container_name: nginx
    environment:
      - DJANGO_URL
      - DJANGO_PORT
      - DJANGO_HOST

  celeryflower:
    image: mwisner/flower:latest
    ports:
      - "5555:5555"
    environment:
      - REDIS_HOST
      - REDIS_DATABASE=1

  celeryworker:
    user: django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    env_file: .env
    command: [celery, -A, sagebrew.tasks, worker, --workdir=/app, --concurrency=4,  -l, INFO]

  celerybeat:
    user: django
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    env_file: .env
    command: [celery, -A, sagebrew.tasks, beat, --workdir=/app, -l, INFO]
