FROM {{PROJECT_NAME}}/django.web.primary.base:v13

MAINTAINER Devon Bleibtrey <devon@sagebrew.com>

RUN apt-get update && apt-get install -y git

RUN mkdir /home/apps/
RUN mkdir /home/apps/logs



RUN git clone -b {{DOCKER_ENV}} git@github.com:{{PROJECT_USERNAME}}/{{PROJECT_REPONAME}}.git /home/apps/{{PROJECT_NAME}}/
RUN chown -R {{APP_USER}}:{{APP_USER}} /home/apps/
RUN mkdir /home/apps/{{PROJECT_NAME}}/{{PROJECT_NAME}}/static/
RUN rm -r /root/.ssh
RUN apt-get remove --auto-remove -y openssh-client

USER {{APP_USER}}
RUN apt-get install -y nodejs
RUN ln -s /usr/bin/nodejs /usr/bin/node
RUN  apt-get install -y npm
RUN npm install -g bower
RUN npm install -g grunt
RUN npm install -g grunt-cli
RUN npm install -g less
WORKDIR /home/apps/{{PROJECT_NAME}}/{{PROJECT_NAME}}/{{PROJECT_NAME}}/static/


RUN bower install --config.interactive=false
WORKDIR /home/apps/{{PROJECT_NAME}}/{{PROJECT_NAME}}/{{PROJECT_NAME}}/static/bower_components/flatui/
RUN npm install
RUN bower install --config.interactive=false
RUN grunt dist
RUN pip install -r /home/apps/{{PROJECT_NAME}}/requirements/{{REQUIREMENTS_FILE}}.txt

USER root
RUN apt-get -y install wget
RUN echo deb http://apt.newrelic.com/debian/ newrelic non-free >> /etc/apt/sources.list.d/newrelic.list
RUN wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -
RUN apt-get update
RUN apt-get install newrelic-sysmond
RUN nrsysmond-config --set license_key={{NEW_RELIC_LICENSE}}
RUN newrelic-admin generate-config {{NEW_RELIC_LICENSE}} /home/apps/newrelic.ini


RUN apt-get remove --auto-remove -y git
RUN apt-get remove --auto-remove -y wget

RUN rm /etc/nginx/sites-enabled/default


# nginx command must come first because running supervisor as a nodaemon means
# it would never get to the && nginx if it were first. We might want to run
# something else endlessly rather than run supervisor as a nodaemon. Not sure
# the reprocutions of this.
WORKDIR /home/apps/{{PROJECT_NAME}}/{{PROJECT_NAME}}/
CMD chown {{APP_USER}} /etc/rsyslog.d/ && python manage.py logglypopulation {{LOG_ACCOUNT}} {{LOG_TOKEN}} && chown root /etc/rsyslog.d/ && service rsyslog restart && chown {{APP_USER}} /etc/supervisor/conf.d/ && python manage.py populatesupervisor {{SUPER_TEMPLATE}} {{APP_USER}} && chown root /etc/supervisor/conf.d/ && chown {{APP_USER}} /etc/nginx/ && python manage.py populatenginx {{APP_USER}} {{SUPER_TEMPLATE}} && chown root /etc/nginx/ && nginx && supervisord -c /etc/supervisor/supervisord.conf --nodaemon
