FROM {{PROJECT_NAME}}/django.web.primary.base:v11

MAINTAINER Devon Bleibtrey <devon@sagebrew.com>

RUN apt-get update && apt-get install -y git

RUN mkdir /home/apps/
RUN mkdir /home/apps/logs


RUN git clone -b {{DOCKER_ENV}} git@github.com:{{PROJECT_USERNAME}}/{{PROJECT_REPONAME}}.git /home/apps/{{PROJECT_NAME}}/
RUN chown -R {{APP_USER}}:{{APP_USER}} /home/apps/

RUN rm -r /root/.ssh
RUN apt-get remove --auto-remove -y openssh-client

RUN pip install -r /home/apps/{{PROJECT_NAME}}/requirements/{{REQUIREMENTS_FILE}}.txt

RUN apt-get -y install wget
RUN echo deb http://apt.newrelic.com/debian/ newrelic non-free >> /etc/apt/sources.list.d/newrelic.list
RUN wget -O- https://download.newrelic.com/548C16BF.gpg | apt-key add -
RUN apt-get update
RUN apt-get install newrelic-sysmond
RUN nrsysmond-config --set license_key={{NEW_RELIC_LICENSE}}
newrelic-admin generate-config {{NEW_RELIC_LICENSE}} /home/apps/newrelic.ini


RUN apt-get remove --auto-remove -y git
RUN apt-get remove --auto-remove -y wget
ENV NEO4J_REST_URL {{NEO4J_REST_URL}}
ENV BOMBERMAN_API_KEY {{BOMBERMAN_API_KEY}}
ENV SSL_CERT_LOCATION {{SSL_CERT_LOCATION}}
ENV SSL_KEY_LOCATION {{SSL_KEY_LOCATION}}
RUN chown {{APP_USER}} /etc/rsyslog.d/
RUN python /home/apps/{{PROJECT_NAME}}/{{PROJECT_NAME}}/manage.py logglypopulation {{LOG_ACCOUNT}} {{LOG_TOKEN}}
RUN chown {{APP_USER}} /etc/nginx/
RUN python /home/apps/{{PROJECT_NAME}}/{{PROJECT_NAME}}/manage.py populatenginx {{APP_USER}}
RUN chown root /etc/rsyslog.d/
RUN chown root /etc/nginx/
RUN service rsyslog restart

RUN chown {{APP_USER}} /etc/supervisor/conf.d/
RUN python /home/apps/{{PROJECT_NAME}}/{{PROJECT_NAME}}/manage.py populatesupervisor {{SUPER_TEMPLATE}} {{APP_USER}}
RUN chown root /etc/supervisor/conf.d/
# nginx command must come first because running supervisor as a nodaemon means
# it would never get to the && nginx if it were first. We might want to run
# something else endlessly rather than run supervisor as a nodaemon. Not sure
# the reprocutions of this.
CMD nginx && supervisord -c /etc/supervisor/supervisord.conf --nodaemon
